- Rakefile
allows developer to start an irb session with the library preloaded
> adds `rake console` command

- lib/opentok/client.rb
- spec/opentok/archives_spec.rb
- spec/opentok/opentok_spec.rb
- spec/spec_helper.rb
Simply adds a default timeout (connect / read) to `HTTParty` to ensure clients don't get unexpected delays in case of network issues. 
I do think it's a very rare event, but given:
* HTTParty supports the option well enough
* There doesn't seem to be an easy way to set this from the outside of the class
I though I would just add the change and open a PR with you guys.
I'm not sure how to spec this out though, I could mock timeouts but that's probably not exactly what I want as it would just mock the exception and not the _actual_ waiting period.
Thoughts from you guys?
> Add HTTP default_timeout

- lib/opentok/client.rb
As raised in https://github.com/opentok/Opentok-Ruby-SDK/issues/105, this PR replaces the default_timeout (open/read) with open_timeout only. 
Given that some issues have been reported from places with extremely poor bandwidth , it also bumps the timeout to 2s.
> Change default_timeout to open_timeout and bump timeout to 2s

- .travis.yml
- lib/opentok/client.rb
- spec/cassettes/OpenTok_Archives/should_create_archives.yml
- spec/cassettes/OpenTok_Archives/should_create_audio_only_archives.yml
- spec/cassettes/OpenTok_Archives/should_create_individual_archives.yml
- spec/cassettes/OpenTok_Archives/should_create_named_archives.yml
- spec/cassettes/OpenTok_Archives/should_delete_an_archive_by_id.yml
- spec/cassettes/OpenTok_Archives/should_find_archives_by_id.yml
- spec/cassettes/OpenTok_Archives/should_find_archives_with_unknown_properties.yml
- spec/cassettes/OpenTok_Archives/should_find_expired_archives.yml
- spec/cassettes/OpenTok_Archives/should_find_paused_archives_by_id.yml
- spec/cassettes/OpenTok_Archives/should_stop_archives.yml
- spec/cassettes/OpenTok_Archives/when_many_archives_are_created/should_return_all_archives.yml
- spec/cassettes/OpenTok_Archives/when_many_archives_are_created/should_return_archives_with_an_offset.yml
- spec/cassettes/OpenTok_Archives/when_many_archives_are_created/should_return_count_number_of_archives.yml
- spec/cassettes/OpenTok_Archives/when_many_archives_are_created/should_return_part_of_the_archives_when_using_offset_and_count.yml
/partner is deprecated and will no longer by supported from July 2017
> Update REST API URL from /partner to /project

- lib/opentok/sip.rb
"X-" prefix for custom headers no longer required
> Correction to SIP docs

- README.md
- lib/opentok/archives.rb
- spec/cassettes/OpenTok_Archives/should_create_custom_layout_archives.yml
- spec/opentok/archives_spec.rb
With help from TokBox support I was not able to set layout when creating an archive. According to the documentation you can pass a `:layout` Hash that will allow for customizing the composed output. This was not part of the Ruby Gem so this adds this option to the whitelist of options when creating the archive.
> Add layout to archive create

- README.md
- lib/opentok/client.rb
- lib/opentok/opentok.rb
- spec/opentok/client_spec.rb
- spec/opentok/opentok_spec.rb
Related to #105 this creates a definable parameter (Integer, num. of seconds) of `timeout_length` that can be provided or it defaults to `2`.
The name `timeout_length` was chosen because `Object#timeout` is already a reserved keyword in Ruby, as its a class method on `Object`.
There was no test suite for `OpenTok::Client` so that was added as well to test the new functionality.
> Add ability to specify custom timeout length for HTTP requests

- lib/opentok/opentok.rb
When creating OpenTok client like this
```
@opentok = ::OpenTok::OpentTok.new api_key, secret_key, timeout_length: 10
```
That custom `timeout_length` setting is not passed into `OpenTok::Client`
```
protected
def client
@client ||= Client.new api_key, api_secret, api_url, ua_addendum
end
```
And that parameter is not used, instead default 2 [s] value is used.
> Passing custom timeout length to OpenTok::Client constructor

- lib/opentok/version.rb
- spec/opentok/opentok_spec.rb
Related to #214 
Also, increment version to correspond to patch release in `dev` branch in preparation for next release into `master`
> New spec to ensure custom timeout_length is passed through OpenTok::OpenTok#client

- lib/opentok/archive.rb
Fixes #222 
PR aligns code comment on `duration` with [API specification](https://tokbox.com/developer/rest/#retrieve_archive_info)
> update archive code comment to conform with api spec

- lib/opentok/sip.rb
- spec/cassettes/OpenTok_Sip/receives_a_valid_response.yml
- spec/opentok/sip_spec.rb
This PR provides clarity around use of the `observe_force_mute` option when making a SIP call using the `Sip#dial` method.
Including `'"observeForceMute":"true"` as part of the JSON payload for call to the `/dial` API endpoint indicates whether the SIP end point observes [force mute moderation](https://tokbox.com/developer/guides/moderation/). This property can be included in the payload by adding it as an option in the `opts` hash passed to `Sip#dial` [method](https://github.com/opentok/OpenTok-Ruby-SDK/blob/142ef849cba11715a31b3513e8d87eec376de793/lib/opentok/sip.rb#L38). No changes were required to the implementation of the method, since the method can already accept `observe_force_mute` as a key in the `opts` hash (the method is very lenient with regards to keys that can be included …
> DEVX-5663 Add SIP observeForceMute flag

- lib/opentok/client.rb
- lib/opentok/sip.rb
- spec/cassettes/OpenTok_Sip/_play_dtmf_to_connection/returns_a_200_response_code_when_passed_a_valid_dtmf_digit_string.yml
- spec/cassettes/OpenTok_Sip/_play_dtmf_to_session/returns_a_200_response_code_when_passed_a_valid_dtmf_digit_string.yml
- spec/opentok/sip_spec.rb
Implements the play DTMF feature, either for an individual connection or for all connections in a session. Two methods have been added, one for each of these actions, as well as a helper method for validating DTMF digits.
It implements a feature in the SDK which has already been added to the API.
> DEVX-5655 Implement dial DTMF digits feature

- lib/opentok/archive.rb
- lib/opentok/archives.rb
- lib/opentok/broadcast.rb
- lib/opentok/broadcasts.rb
- lib/opentok/client.rb
- spec/cassettes/OpenTok_Archives/adds_a_stream_to_an_archive.yml
- spec/cassettes/OpenTok_Archives/removes_a_stream_from_an_archive.yml
- spec/cassettes/OpenTok_Broadcasts/adds_a_stream_to_a_broadcast.yml
- spec/cassettes/OpenTok_Broadcasts/removes_a_stream_from_a_broadcast.yml
- spec/opentok/archives_spec.rb
- spec/opentok/broadcasts_spec.rb
Implements the play Archive/ Broadcast selective stream feature. This feature allows for streams to be added to or removed from archives or broadcasts started in manual mode.
It implements a feature in the SDK which has already been added to the API.
> DEVX-5711 Implement selective stream feature for Archive and Broadcast

- lib/opentok/streams.rb
- opentok.gemspec
- spec/cassettes/OpenTok_Streams/disables_the_mute_state_of_a_session.yml
- spec/cassettes/OpenTok_Streams/forces_all_current_and_future_streams_in_a_session_to_be_muted.yml
- spec/cassettes/OpenTok_Streams/forces_all_current_and_future_streams_in_a_session_to_be_muted_except_for_the_specified_excluded_streams.yml
- spec/opentok/streams_spec.rb
Updates the force mute feature, to set the `force_mute_all` method to have `active` set to `true` by default (in order to mute all future streams) and to add an additional method `disable_force_mute`, which sets `active` to `false` in order to disable the mute state of the session (so that future streams are not automatically muted).
It implements a feature in the SDK which has already been added to the API. The main elements of the feature were added in #233, but this PR makes amendments to the feature to bring it in line with the actual API (some aspects of the previous implementation were erroneous due to and inaccuracies in the documentation).
> DEVX-5446  Making amendments to force mute feature to disable mute state

- lib/opentok/broadcast_list.rb
- lib/opentok/broadcasts.rb
- lib/opentok/client.rb
- lib/opentok/token_generator.rb
- lib/opentok/version.rb
- sample/Broadcast/README.md
- sample/Broadcast/broadcast_sample.rb
- sample/Broadcast/views/all.erb
- sample/Broadcast/views/index.erb
- spec/cassettes/OpenTok_Broadcasts/for_many_broadcasts/should_return_all_broadcasts.yml
- spec/cassettes/OpenTok_Broadcasts/for_many_broadcasts/should_return_broadcasts_with_an_offset.yml
- spec/cassettes/OpenTok_Broadcasts/for_many_broadcasts/should_return_count_number_of_broadcasts.yml
- spec/cassettes/OpenTok_Broadcasts/for_many_broadcasts/should_return_part_of_the_broadcasts_when_using_offset_and_count.yml
- spec/cassettes/OpenTok_Broadcasts/for_many_broadcasts/should_return_session_broadcasts.yml
- spec/opentok/broadcasts_spec.rb
This PR adds a missing client implementation for [ Listing live streaming broadcasts](https://tokbox.com/developer/rest/#list_broadcasts) support. 
The solution is heavily based on the `List archives` codebase.
The added specs are disabled right now, since I don't have any test credentials to generate the test mocks.
Any insights or feedbacks on making this Pull Request are welcomed.
> feat: add `Listing live streaming broadcasts` support

- README.md
- lib/opentok/archives.rb
- lib/opentok/broadcasts.rb
- lib/opentok/opentok.rb
- lib/opentok/streams.rb
- lib/opentok/version.rb
- spec/opentok/broadcasts_spec.rb
- Adds `dvr` and `lowlatency` options for `hls` Broadcast objects
- Updates code comments for usage of these options
- Adds a check that both are not set to `true` simultaneously
It implements a feature in the SDK which has already been added to the API.
Added a test for the conditional check.
> DEVX-5926 and DEVX-5937 Add dvr and lowlatency options for HLS Broadcasts

- README.md
- lib/opentok/archive.rb
- lib/opentok/archives.rb
- lib/opentok/broadcast.rb
- lib/opentok/broadcasts.rb
Updates code comments for the `resolution` property when creating new Archives and Broadcasts to add options for `1920x1080` and `1080x1920`
To keep the code comments in line with the actual resolution options specified in the documentation
No testing required. Code comment updates only.
> DEVX-5914 Add 1080p for Archive and Broadcast

- lib/opentok/archive.rb
- lib/opentok/archives.rb
- lib/opentok/broadcast.rb
- lib/opentok/broadcasts.rb
- spec/cassettes/OpenTok_Archives/should_create_an_archives_with_a_matching_multi_archive_tag_tag_value_when_multiArchiveTag_is_specified.yml
- spec/cassettes/OpenTok_Archives/should_create_an_archives_with_a_multi_archive_tag_tag_value_of_nil_when_multiArchiveTag_is_not_specified.yml
- spec/cassettes/OpenTok_Archives/should_create_an_archives_with_a_specified_multiArchiveTag.yml
- spec/cassettes/OpenTok_Broadcasts/starts_a_broadcast_with_a_matching_multi_broadcast_tag_value_when_multiBroadcastTag_is_specified.yml
- spec/cassettes/OpenTok_Broadcasts/starts_a_broadcast_with_a_multi_broadcast_tag_tag_value_of_nil_when_multiBroadcastTag_is_not_specified.yml
- spec/cassettes/OpenTok_Broadcasts/starts_a_broadcast_with_a_specified_multiBroadcastTag.yml
- spec/opentok/archives_spec.rb
- spec/opentok/broadcasts_spec.rb
Adds code comments for the `multiArchiveTag` and `multiBroadcastTag` properties when creating Archives and Broadcasts.
To keep the code comments in line with the actual options specified in the documentation
Added tests to ensure that Archives can be created with a `multiArchiveTag` specified and Broadcasts can be created with a `multiBroadcastTag` specified.
> DEVX-6487: Adding support for multiple archives and records feature

- lib/opentok/client.rb
- lib/opentok/exceptions.rb
- lib/opentok/opentok.rb
- lib/opentok/render.rb
- lib/opentok/render_list.rb
- lib/opentok/renders.rb
- spec/cassettes/OpenTok_Renders/finds_an_Experience_Composer_render.yml
- spec/cassettes/OpenTok_Renders/for_many_renders/should_return_all_renders.yml
- spec/cassettes/OpenTok_Renders/for_many_renders/should_return_count_number_of_renders.yml
- spec/cassettes/OpenTok_Renders/for_many_renders/should_return_part_of_the_renders_when_using_offset_and_count.yml
- spec/cassettes/OpenTok_Renders/for_many_renders/should_return_renders_with_an_offset.yml
- spec/cassettes/OpenTok_Renders/starts_an_Experience_Composer_render.yml
- spec/cassettes/OpenTok_Renders/stops_an_Experience_Composer_render.yml
- spec/opentok/renders_spec.rb
Implements the Experience Composer render feature. 
It implements a feature in the SDK which has already been added to the API.
> DEVX-6493: Add Experience Composer functionality

- README.md
- lib/opentok/opentok.rb
- lib/opentok/session.rb
- spec/cassettes/OpenTok_OpenTok/when_initialized_properly/_create_session/creates_e2ee_sessions.yml
- spec/opentok/opentok_spec.rb
- Updates the `Opentok#create_session` method to:
- Add an option for `:e2ee` to `valid_opts`
- Adds conditional checks to the method ensure `:e2ee` is not set to `true` if `:media_mode` is `:relayed` or if `:archive_mode` is `:always`
- Update the docs comments to provide information on the new param and a link to the relevant OpenTok documentation
- Adds unit tests for the new functionality described above
It implements a feature in the SDK which is being added to the API.
Added a number tests for calling `Opentok#create_session` with the new `:e2ee` param set, as well as tests for invalid configuration options
n/a
> DEVX-6810: Add support for E2EE

- README.md
- Updates the `README.md` file to:
- Provide guidance on appending a custom string to the `User-Agent` header
We need to add the ability to append to the user agent in the OpenTok SDKs. This is so the partner's team can track usage. 
The Ruby SDK already provides this functionality, but it wasn't previously documented in the README. This PR fixes that.
There is already a unit test for this behaviour.
n/a
> DEVX-6966: Append to user agent

- lib/opentok/opentok.rb
- lib/opentok/session.rb
- spec/cassettes/OpenTok_OpenTok/when_initialized_properly/_create_session/creates_always_archived_sessions_with_a_set_archive_name.yml
- spec/cassettes/OpenTok_OpenTok/when_initialized_properly/_create_session/creates_always_archived_sessions_with_a_set_archive_name_and_resolution.yml
- spec/cassettes/OpenTok_OpenTok/when_initialized_properly/_create_session/creates_always_archived_sessions_with_a_set_archive_resolution.yml
- spec/opentok/opentok_spec.rb
- Updates the `Opentok#create_session` method to:
- Add options for `:archive_name` and `archive_name` to `valid_opts`
- Adds conditional checks to the method ensure `:archive_mode` is not set to `:manual` if `:archive_name` and/or `archive_name` are set
- Update the docs comments to provide information on the new params
- Updates the `Session` class to:
- Add instance variables for the new params in the `initialize` method
- Add getter methods for the new params
- Adds unit tests for the new functionality described above
It implements a feature in the SDK which has been added to the API.
Added a number tests for calling `Opentok#create_session` with the new params set, as well as tests for invalid configuration options
n/a
> DEVX-6817: Auto Archive Improvements

- CHANGES.md
- lib/opentok/broadcast.rb
- lib/opentok/broadcasts.rb
- lib/opentok/sip.rb
- lib/opentok/version.rb
- Updates the `broadcasts.rb` file to add properties in the docs comments for the `create` method, specifically:
- `maxBitRate`
- `hasAudio`
- `hasVideo`
- Updates the `broadcast.rb` file to add properties in the docs comments for the `Broadcast` class description, specifically:
- `maxBitRate`
- `hasAudio`
- `hasVideo`
- `hlsStatus`
- Updates the `sip.rb` file to add properties in the docs comments for the `dial` method, specifically:
- `streams`
To keep the docs comments in the library in line with recent changes to the API.
N/A: comment updates only
n/a
> DEVX-6823/DEVX-7080/DEVX-6829/DEVX-6830: Broadcast and Dial updates

- CHANGES.md
- lib/opentok/captions.rb
- lib/opentok/client.rb
- lib/opentok/exceptions.rb
- lib/opentok/opentok.rb
- lib/opentok/version.rb
- spec/cassettes/OpenTok_Captions/receives_a_valid_response_when_starting_captions.yml
- spec/cassettes/OpenTok_Captions/receives_a_valid_response_when_starting_captions_with_options.yml
- spec/cassettes/OpenTok_Captions/receives_a_valid_response_when_stopping_captions.yml
- spec/opentok/captions_spec.rb
Implements the Captions API functionality. Specifically:
- Implements a `Caption` class with `start` and `stop` wrapper functions
- Updates the `Client class to add `start_live_captions` and `stop_live_captions` which are called by the `Captions` wrappers
- Updates the `Opentok` class to add a `captions` method which returns a `Captions` object
- Adds a `OpenTokCaptionsError` class
- Adds unit tests for the new functionality
Adds a feature to the SDK which has recently gone GA in the API.
Unit tests added for the new functionality.
n/a
> DEVX-6803: Adding Captions API

- lib/opentok/archives.rb
- spec/cassettes/OpenTok_Archives/should_create_an_archive_with_matching_multi_archive_tag_when_multiArchiveTag_is_specified.yml
- spec/cassettes/OpenTok_Archives/should_create_an_archives_with_a_specified_multiArchiveTag.yml
Fixes issue #268 
The tests on the repo are deceptive, you can remove setting multiArchiveTag at all and they will still work since the VCR response has the archive tag set in the response.
This PR allows these attributes correctly through creation and ensures they are passed on to the http request to the api.
> Accept all valid options for archive creation.

- CHANGES.md
- lib/opentok/archive.rb
- lib/opentok/archives.rb
- lib/opentok/version.rb
- spec/cassettes/OpenTok_Archives/should_create_an_archive_with_streamMode_set_to_specified_stream_mode_value.yml
- spec/opentok/archives_spec.rb
This PR follows on from #269 to provide more idiomatic usage of `options` hash for the `Archives#create` method. Specifically it:
- Changes `multi_archive_tag` and `stream_mode` in the `valid_opts` array defined in  `Archives#create` to snake_case from camelCase
- Adds an ivar and attr_accessor for `stream_mode` in the `Archive` class
- Adds a test for creating an archive with a specific `stream_mode`
#269 fixed a bug whereby the `mutliArchiveTag` and `streamMode` properties weren't being passed to the API endpoint. This PR makes the setting of those properties via the `Archives#create` method more idiomatic.
Unit tests added and//or ammended to test the functionality.
n/a
> Release 4.8.1

- CHANGES.md
- lib/opentok/constants.rb
- lib/opentok/version.rb
- spec/shared/opentok_generates_tokens.rb
This PR adds the `publisheronly` role as a valid option for client token generation.
Implements functionality in the SDK which has recently been added to the API.
Unit tests added and//or ammended to test the functionality.
n/a
> Add publisheronly token role

- .github/workflows/ci.yml
- CHANGES.md
- Gemfile
- lib/opentok/opentok.rb
- lib/opentok/session.rb
- lib/opentok/token_generator.rb
- lib/opentok/version.rb
- spec/matchers/token.rb
- spec/opentok/session_spec.rb
- spec/shared/opentok_generates_tokens.rb
- spec/shared/session_generates_tokens.rb
This PR adds the ability to create JWT client tokens and sets this as the default, with the option to create T1 tokens if the user specifies this. Specifically the PR:
- Updates the token creation logic to accept an optional `token_type` param in the `generate_token` method:
- The param has two acceptable values: 'T1' and 'JWT'
- If 'T1' is set, a T1 token is generated
- If 'JWT' is set, or if the `token_type` param is ommitted, a JWT is generated
- Updates existing unit tests and add new unit tests to cover the amended and added functionality
> DEVX-8994: Change default client tokens to JWT

- .github/workflows/ci.yml
- CHANGES.md
- Gemfile
- lib/opentok/opentok.rb
- lib/opentok/session.rb
- lib/opentok/token_generator.rb
- lib/opentok/version.rb
- spec/matchers/token.rb
- spec/opentok/session_spec.rb
- spec/shared/opentok_generates_tokens.rb
- spec/shared/session_generates_tokens.rb
Reverts opentok/OpenTok-Ruby-SDK#274
> Revert "DEVX-8994: Change default client tokens to JWT"

- CHANGES.md
- lib/opentok/archives.rb
- lib/opentok/version.rb
- spec/cassettes/OpenTok_Archives/should_create_an_archive_with_maxBitrate_set_to_specified_max_bitrate_value.yml
- spec/opentok/archives_spec.rb
This PR adds the ability to set a `maxBitrate` property when creating an archive. Specifically it:
- Updates the `Archives#create` method to allow `max_bitrate` as a valid option
- Updates the code comments on that method to explain the option
- Adds a unit test for creating an archive with a specific max bitrate
> DEVX-9004: Implementing max bitrate for archives
